Environment:
  task: "CombatSpider"
  task_parameter:
    image_size: [224,224]
    step_penalty: 0
    attack_reward: 1
    success_reward: 10
    # max_spawn_range: 10
    # target_quantities: 1
    # max_episode_len: 500
  num_envs: 1
  seed: 123
 
  action_space: "ReducedActionSpace"
  observation: "ImageObservation"

PPO_Training:
  save_name: "1M_CNN_CombatSpider"
  policy: "CnnPolicy" # CnnPolicy / MlpPolicy
  training_step: 1000000 #1M
  eval_episode: 10