Environment:
  task: HuntCows
  task_parameter:
    image_size:
    - 600
    - 1024
    step_penalty: 0
    nav_reward_scale: 0.5
    attack_reward: 1
    success_reward: 10
    mob_quantities: 6
  num_envs: 1
  seed: 123
  action_space: ReducedActionSpace
  observation: ImageObservation
  frame_stack: 4
PPO_Training:
  save_name: 100K_CLIP_HuntCow
  total_timesteps: 1000000
  eval_episodes: 10
  algo:
    gamma: 0.985
    gae_lambda: 0.95
    ent_coef: 3E-4
  policy:
    class_path: utils.policies.DreamerActorCritic
    ortho_init: false
    net_kwargs:
      hid_dim: 1024
      num_layers: 3
      activation: silu
      norm: rmsnorm
      share_backbone: false
    features_extractor:
      class_path: utils.extractors.CLIPFeatureExtractor
      kwargs:
        features_dim: 1024
        clip_model_path: "/path/to/pretrain clip mdoel" 
        project_activation: relu
